repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
    -   id: ruff
        args: [--fix, --line-length=79]
    -   id: ruff-format
        args: [--line-length=79]

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.2
    hooks:
    -   id: pylint
        args:
        -   --max-line-length=79
        -   --disable=C0111,R0903,C0103

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
    -   id: pylama
        args: [--max-line-length=79]